### ISSUE TITLE
Naming Problems

### ISSUE THREAD

**Issue by mike-thompson-day8** [brillout/reframe#1]
Your choice of name will likely create confusion because `re-frame`  is a well established React framework sometimes compared to Redux, albeit in ClojureScript:   https://github.com/Day8/re-frame 

It has previously made it onto the [main stage at React conferences](https://www.youtube.com/watch?v=-jwQ3sGoiXg).  If you Google for "React re-frame"  you'll get a sense of the possible future confusion ahead. 

Indeed, there are already clones of re-frame pattern in the `js` world:  http://karolmajta.github.io/reframe-js/

**Comment by brillout** [comment]
I've given this some thoughts.

I'm aware of `re-frame` and so far I found it ok that they have similar names.

They live in different worlds (ClojureScript vs JavaScript) and do quite different things:
 - `re-frame` is doing SPAs with state management.
 - `Reframe` is doing isomorphic React apps.
The point here is that they are not interchangeable: Someone looking for something like `re-frame` is not suddenly going to think "I'm going to use Reframe instead" and the same the other way around. It's not like someone creating a new beverage brand called "Coka-Cola" in the hopes that someone will confuse "Coka-Cola" with "Coca-Cola". I don't believe it to be the case and it is certainly not my intention.

Web dev is a complex field and I think we can reasonably expect our users to remember "re-frame = SPA + state management in ClojureScript, Reframe = iso React apps for JavaScript".

In the end, I struggle to see concrete negative implications here.

I'm open for further discussion but for now this is a non-issue in my head.

Thanks for opening this ticket.
