### ISSUE TITLE
[cli] Move `pages` and `views` to root?

### ISSUE THREAD

**Issue by brillout** [brillout/reframe#11]
Was thinking, do we really need the `app` directory?

@tdfranklin

**Comment by tdfranklin** [comment]
I'd say it's a matter of personal preference.  I guess my thought process was that the "app" folder would hold basically any front-end code for you app, and then if you wanted back-end code (like to connect to a database or something) you might want to add a server or model folder or something like that.  If you want to dump the "app" folder for now, though, just let me know and I can make that change really quick.

**Comment by brillout** [comment]
My thinking: Because Reframe is a full-stack framework, the distinction between front-end and back-end code is less relevant: The page configs are used both in the browser and on the server.

From my perspective a project folder structure like the following feels cozy:
 - pages
   - landing.js
   - about.js
 - views
   - landing
   - about
   - header
   - footer
 - server.js
 - models
 - auth
   - oauth.js
 - package.json
 - .git
 - etc.

Feel free to object

**Comment by tdfranklin** [comment]
Oh, ok!  I certainly like that structure!  Let's discuss what you want each of those files to look like and I'll get the changes made!

**Comment by brillout** [comment]
I'd say let's keep this ticket only about moving `pages` and `views` to the root, i.e. removing the app directory.

And let's use https://github.com/brillout/reframe/issues/10 for further discussions.

**Comment by tdfranklin** [comment]
Ok PR submitted.

**Comment by brillout** [comment]
Done
