### ISSUE TITLE
[cli] command for production build

### ISSUE THREAD

**Issue by brillout** [brillout/reframe#13]
Same than `reframe start` but for production. In other words, the command would `process.env.NODE_ENV = 'production';` and then do the same than start.

@tdfranklin

**Comment by tdfranklin** [comment]
Ok, would you prefer to have an entirely different command for this or just have a flag for `reframe start`?

For instance, would you rather it look like this:
`reframe start` = start server on dev
`reframe start -p` = start server on prod

Or an entirely separate command:
`reframe start` = start server on dev
`reframe prod` = start server on prod (or whatever command you think would be best)

In my opinion I think it makes more sense to just add a flag to our current `start` command, but it will be easy enough to implement it either way.

**Comment by brillout** [comment]
> In my opinion I think it makes more sense to just add a flag

Ok let's do it that way then

**Comment by brillout** [comment]
Done
