### ISSUE TITLE
[cli] add --log option for `reframe start`...

### ISSUE THREAD

**Issue by brillout** [brillout/reframe#15]
...which would be passed down to `createHapiServer`.

(When `createHapiServer` is passed the argument `log: true` it prints build and page information.)
(`createHapiServer` is called in the `cli.js` file.)

**Comment by brillout** [comment]
@tdfranklin if you are up for it:)

**Comment by tdfranklin** [comment]
Ok, there ya go!  See if that PR is what you're looking for and let me know if you want any changes.

**Comment by brillout** [comment]
Done
